### ISSUE TITLE
Bad receiver range on CC1101

### ISSUE THREAD

**Issue by peranil** [matthias-bs/Bresser_Weather_Sensor_CC1101_MQTT#3]
Hi,

Thanks for some great coding! I have been using it for a week now and it has been running very stable! What is your experience with the range of the CC1101 transceiver module? For me it needs to be placed in a window with direct sight to the outdoor weather sensor in order to have a decent quality of the received data. Any ways to improve that or perhaps its better to use another transceiver?

Br.
Per

**Comment by matthias-bs** [comment]
Hi,

Thanks for the nice feedback. I have good reception at a distance of ~25 m to the weather station, but I had similar issues during development.

Sometimes it helps to move the receiver a few centimeters to a different position or to change the antenna's orientation. You can also try a different type of antenna - wire antenna vs. helical coil antenna. Unfortunately there does not seem to be a CC1101 board with a proper antenna connector.

The YouTube video [#182 ESP32 Lora Boards: What you need to know before you buy (incl. Antenna knowledge)](https://www.youtube.com/watch?v=CJNq2I_PDHQ) by Andreas Spiess also suggests that some antennas out there are not as good as you could hope for...

I additionally noticed that radiated emissions from other electronic devices (PC, other microcontroller boards, ...) near the receiver had significant influence on signal quality. I even noticed that the power supply had some influence (USB power from my notebook was bad, USB power from my desktop PC or wall adapter was fine).

BUT - I got almost rock solid reception when I changed to the [Adafruit RFM95W LoRa Radio Transceiver Breakout](https://www.adafruit.com/product/3072) with a proper antenna ([Delock LoRa 868 MHz Antenna SMA plug 3 dBi omnidirectional with tilt joint black](https://www.delock.de/produkt/89769/merkmale.html?setLanguage=en) in my case). I don't know if this is due to better chip design, better PCB design or just the antenna.

Please check the repository [matthias-bs/BresserWeatherSensorReceiver](/matthias-bs/BresserWeatherSensorReceiver). This is actually recommended as replacement for [matthias-bs/Bresser_Weather_Sensor_CC1101_MQTT](/matthias-bs/Bresser_Weather_Sensor_CC1101_MQTT) anyway (which I have not communicated yet...)!

Best regards
Matthias

**Comment by peranil** [comment]
Thanks for the detailed answer! I will experiment with different antennas and the position. I will also switch to the new library soon.

Br.
Per
